spring:
    application:
        name: gateway
    threads:
        virtual:
            enabled: true
    data:
        redis:
            host: localhost
            database: 15
            port: 6379
    config:
        import:
            - "consul:localhost:18500"
    cloud:
        consul:
            host: localhost
            port: 18500
            config:
                format: yaml
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: true
                            lower-case-service-id: true
server:
    port: 10086
logging:
    level:
        root: info
