spring:
    application:
        name: gateway
    threads:
        virtual:
            enabled: true
    data:
        redis:
            host: localhost
            database: 15
            port: 6379
    cloud:
        consul:
            discovery:
                health-check-critical-timeout: 30s
                prefer-ip-address: true
                instance-id: ${spring.application.name}:${random.uuid}
            host: localhost
            port: 18500
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: true
                            lower-case-service-id: true
server:
    port: 10086
logging:
    level:
        root: info
