spring:
    application:
        name: gateway
    config:
        import:
            - "consul:localhost:18500"
    cloud:
        consul:
            host: localhost
            port: 18500
            config:
                format: yaml
